name: deploy hetzner

on:
  push:
    branches: [ hetzner ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'corretto'
    - run: |
        ./gradlew build -x checkstyleMain --no-daemon

    - name: Add env vars
      run: |
        echo "Environment=DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> ./setup/traccar.service
        echo "Environment=DOMAIN=${{ vars.DOMAIN }}" >> ./setup/traccar.service
        echo "Environment=EMAIL=${{ secrets.EMAIL }}" >> ./setup/traccar.service

    - name: Build installers
      working-directory: ./setup
      run: |
        sudo apt-get install makeself
        wget -q https://corretto.aws/downloads/resources/11.0.25.9.1/amazon-corretto-11.0.25.9.1-linux-x64.tar.gz
        mkdir -p out/{conf,data,lib,logs,web,schema,templates,setup}
        cp -v ../target/tracker-server.jar out
        cp -v ../target/lib/* out/lib
        cp -v ../traccar.xml out/conf
        cp -v default.xml out/setup
        cp -v setup.sh traccar.service out
        tar -xf amazon-corretto-11.0.25.9.1-linux-x64.tar.gz
        echo "jlink"
        jlink --module-path jdk-*/jmods --add-modules java.se,jdk.charsets,jdk.crypto.ec,jdk.unsupported --output out/jre
        rm -rf jdk-*
        echo "makeself"
        makeself --needroot --quiet --notemp out traccar.run "traccar" ./setup.sh
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        SOURCE: "setup/traccar.run"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        SCRIPT_AFTER: |
          sudo /home/${{ secrets.REMOTE_USER }}/traccar.run
          sudo service traccar start
          echo $RSYNC_STDOUT
