name: Java CI with Gradle

on:
  push:
    branches: [ fleetmap ]
  pull_request:
    branches: [ fleetmap ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SSL_PRIV_KEY: ${{ secrets.SSL_PRIVATE_KEY }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: ./gradlew build -x checkstyleMain
    - run: |
        wget https://github.com/traccar/traccar-web/archive/refs/heads/master.zip
        unzip master.zip
        rm master.zip
    - uses: actions/setup-node@v4
    - run: |
        cd traccar-web-master/modern
        npm install
        npm run build
        cp -r build/* ../../traccar-web
    - run: |
        echo "$SSL_PRIV_KEY" > setup/privkey.pem
        zip -r deploy.zip . -x '*.git*' -x 'traccar-web-master/*' -x 'src/*' -x '.gradle/*' -x 'gradle/*'
    - uses: einaregilsson/beanstalk-deploy@v21
      name: deploy eu
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: traccar-tf
        environment_name: Traccar-env
        version_label: ${{ github.run_number }}
        region: eu-west-3
        deployment_package: deploy.zip
      continue-on-error: true
    - run: |
        rm deploy.zip
        echo ${{ github.NGINX_FORWARD }} > .platform/nginx/nginx-forward.conf
        cat .platform/nginx/nginx-forward.conf
        zip -r deploy.zip . -x '*.git*' -x 'traccar-web-master/*' -x 'src/*' -x '.gradle/*' -x 'gradle/*'
    - uses: einaregilsson/beanstalk-deploy@v21
      name: deploy sa
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: traccar-tf
        environment_name: Traccar-env
        version_label: ${{ github.run_number }}
        region: sa-east-1
        deployment_package: deploy.zip
