name: deploy

on:
  push:
    branches: [ aws2 ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: nginx
    env:
      SSL_PRIV_KEY: ${{ secrets.SSL_PRIVATE_KEY }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'corretto'
    - run: ./gradlew build -x checkstyleMain
    - run: |
        echo "$SSL_PRIV_KEY" > setup/privkey.pem
        zip -r deploy.zip . -x '*.git*' -x 'traccar-web-master/*' -x 'src/*' -x '.gradle/*' -x 'gradle/*'
    - uses: einaregilsson/beanstalk-deploy@v21
      name: deploy eu
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: traccar-tf
        environment_name: Traccar-env
        version_label: ${{ github.run_number }}
        region: eu-west-3
        deployment_package: deploy.zip
